# Generated by Django 5.1.6 on 2025-02-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(related_name="flights", to="airport.crew"),
        ),
    ]
